### ISSUE TITLE
s/defrecord and core.async/go

### ISSUE THREAD

**Issue by d-t-w** [Prismatic/schema#183]
If I have a very simply defrecord, like:

```clojure
(defrecord SomeRecord [a-chan]
  event/Sink
  (send [_ _]
    (async/go (async/<! a-chan))))
```
and I use s/defrecord

```clojure
(s/defrecord SomeRecord [a-chan]
  event/Sink
  (send [_ _]
    (async/go (async/<! a-chan))))
```

I get the following error (can't resolve a-chan variable). If I remove s/defrecord or async/go then it works fine, but combined causes this error:

```
Caused by: clojure.lang.ExceptionInfo: Could not resolve var: a-chan {:file "smx/netty/http/client.clj", :column 15, :line 155, :var a-chan}
	at clojure.core$ex_info.invoke(core.clj:4566)
	at clojure.tools.analyzer.passes.jvm.validate$eval6011$fn__6013.invoke(validate.clj:32)
	at clojure.lang.MultiFn.invoke(MultiFn.java:229)
	at clojure.tools.analyzer.passes.jvm.validate$validate.invoke(validate.clj:240)
	at clojure.tools.analyzer.jvm$run_passes$analyze__7196$fn__7197.invoke(jvm.clj:422)
	at clojure.tools.analyzer.ast$postwalk.invoke(ast.clj:98)
	at clojure.tools.analyzer.ast$postwalk$walk__4431.invoke(ast.clj:97)
	at clojure.core$mapv$fn__6657.invoke(core.clj:6558)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:58)
	at clojure.core.protocols$fn__6433.invoke(protocols.clj:103)
	at clojure.core.protocols$fn__6395$f__6255__auto____G__6390__6404.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6414.invoke(protocols.clj:65)
	at clojure.core.protocols$fn__6369$f__6255__auto____G__6364__6382.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6461)
	at clojure.core$mapv.invoke(core.clj:6558)
	at clojure.tools.analyzer.ast$eval4405$fn__4406$fn__4408.invoke(ast.clj:51)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
	at clojure.core.protocols$fn__6433.invoke(protocols.clj:103)
	at clojure.core.protocols$fn__6395$f__6255__auto____G__6390__6404.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6414.invoke(protocols.clj:65)
	at clojure.core.protocols$fn__6369$f__6255__auto____G__6364__6382.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6461)
	at clojure.tools.analyzer.ast$eval4405$fn__4406.invoke(ast.clj:53)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at clojure.tools.analyzer.ast$update_children.invoke(ast.clj:73)
	at clojure.tools.analyzer.ast$postwalk.invoke(ast.clj:98)
	at clojure.tools.analyzer.ast$postwalk$walk__4431.invoke(ast.clj:97)
	at clojure.tools.analyzer.ast$eval4405$fn__4406$fn__4408.invoke(ast.clj:51)
	at clojure.lang.ArrayChunk.reduce(ArrayChunk.java:63)
	at clojure.core.protocols$fn__6433.invoke(protocols.clj:103)
	at clojure.core.protocols$fn__6395$f__6255__auto____G__6390__6404.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__6414.invoke(protocols.clj:65)
	at clojure.core.protocols$fn__6369$f__6255__auto____G__6364__6382.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6461)
	at clojure.tools.analyzer.ast$eval4405$fn__4406.invoke(ast.clj:53)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at clojure.tools.analyzer.ast$update_children.invoke(ast.clj:73)
	at clojure.tools.analyzer.ast$postwalk.invoke(ast.clj:98)
	at clojure.tools.analyzer.ast$postwalk.invoke(ast.clj:95)
	at clojure.tools.analyzer.jvm$run_passes$analyze__7196.invoke(jvm.clj:413)
	at clojure.tools.analyzer.jvm$run_passes.invoke(jvm.clj:402)
	at clojure.tools.analyzer.jvm$analyze$fn__7205.invoke(jvm.clj:463)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1864)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.analyzer.jvm$analyze.invoke(jvm.clj:458)
	at clojure.core.async.impl.ioc_macros$state_machine.invoke(ioc_macros.clj:1062)
	at clojure.core.async$go.doInvoke(async.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:442)
	at clojure.lang.Var.invoke(Var.java:388)
	at clojure.lang.AFn.applyToHelper(AFn.java:160)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6606)
```

**Comment by w01fe** [comment]
Thanks for the report.  Is this Clojure, and what version?   

It sounds like a workaround for now might be to define your method body as a function and just call that directly from the defrecord?

**Comment by d-t-w** [comment]
Thanks, sorry I should have been more explicit.

I'm using:

[org.clojure/clojure "1.7.0-alpha3"]
[org.clojure/core.async "0.1.346.0-17112a-alpha"]
[prismatic/schema "0.3.1"]

for the time being I just removed schema from that particular defrecord.

**Comment by w01fe** [comment]
Thanks for the details.  It looks like this is an issue with potemkin
defrecord+, which schema uses by default as its record type (but that is
going away in the next version).

For now, can you try setting schema.macros/*use-potemkin* to false and see
if that helps?

Thanks,
Jason

**Comment by d-t-w** [comment]
Good to hear that potemkin is being removed, I've some AOT'd storm topologies which I had to remove schema from because schema+AOT wasn't working, and I think that's related to potemkin and http://dev.clojure.org/jira/browse/CLJ-1227

**Comment by w01fe** [comment]
Potemkin has now been removed from Schema.  If you're still seeing issues with the latest version, please reopen and provide details.  Thanks!
