### ISSUE TITLE
Unhelpful error messages on clojurescript and nodejs

### ISSUE THREAD

**Issue by matklad** [Prismatic/schema#234]
Currently I get an uninformative error messages for clojurescript for failed validation:

```
stest.core-cljs> (s/with-fn-validation (foo 92))
Error
    at new cljs$core$ExceptionInfo (/home/matklad/projects/stest/.cljs_node_repl/cljs/core.js:33112:10)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/home/matklad/projects/stest/.cljs_node_repl/cljs/core.js:33174:9)
    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (/home/matklad/projects/stest/.cljs_node_repl/cljs/core.js:33170:26)
    at cljs$core$ex_info (/home/matklad/projects/stest/.cljs_node_repl/cljs/core.js:33156:26)
    at stest$core_cljs$foo (/home/matklad/projects/stest/.cljs_node_repl/stest/core_cljs.js:39:25)
    at repl:4:32
    at repl:6:4
    at repl:15:3
    at repl:20:4
    at Object.exports.runInThisContext (vm.js:74:17)
```

As you can see, there is no information about what exactly went wrong. For the comparison, the error for the same code in clojure looks like this
```
1. Unhandled clojure.lang.ExceptionInfo
   Output of foo does not match schema: (not (sequential? 92))
   {:type :schema.core/error,
    :schema
    [{:schema
      {:p?
       #object[clojure.core$integer_QMARK_ 0x101f37bb "clojure.core$integer_QMARK_@101f37bb"],
       :pred-name integer?},
      :optional? false,
      :name "i"}
     {:schema java.lang.String, :optional? false, :name "s"}],
    :value 92,
    :error (not (sequential? 92))}

                      core.clj:   12  stest.core/eval24088/foo
                          REPL:    1  stest.core/eval25134
                 Compiler.java: 6782  clojure.lang.Compiler/eval
                 Compiler.java: 6745  clojure.lang.Compiler/eval
                      core.clj: 3081  clojure.core/eval
                      main.clj:  240  clojure.main/repl/read-eval-print/fn
                      main.clj:  240  clojure.main/repl/read-eval-print
                      main.clj:  258  clojure.main/repl/fn
                      main.clj:  258  clojure.main/repl
                   RestFn.java: 1523  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   58  clojure.tools.nrepl.middleware.interruptible-eval/evaluate/fn
                      AFn.java:  152  clojure.lang.AFn/applyToHelper
                      AFn.java:  144  clojure.lang.AFn/applyTo
                      core.clj:  630  clojure.core/apply
                      core.clj: 1868  clojure.core/with-bindings*
                   RestFn.java:  425  clojure.lang.RestFn/invoke
        interruptible_eval.clj:   56  clojure.tools.nrepl.middleware.interruptible-eval/evaluate
        interruptible_eval.clj:  191  clojure.tools.nrepl.middleware.interruptible-eval/interruptible-eval/fn/fn
        interruptible_eval.clj:  159  clojure.tools.nrepl.middleware.interruptible-eval/run-next/fn
                      AFn.java:   22  clojure.lang.AFn/run
       ThreadPoolExecutor.java: 1142  java.util.concurrent.ThreadPoolExecutor/runWorker
       ThreadPoolExecutor.java:  617  java.util.concurrent.ThreadPoolExecutor$Worker/run
                   Thread.java:  745  java.lang.Thread/run
```

If I catch and examine the clojurescript exception, I see that it has a proper message:

```
stest.core-cljs> (.-message exn)
"Output of foo does not match schema: (not (sequential? 92))"
```

However, the stack property does not include this invaluable information :(

```
stest.core-cljs> (.-stack ex)
"Error\n    at new cljs$core$ExceptionInfo (/home/matklad/projects/stest/.cljs_node_repl/cljs/core.js:33112:10)\n    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$3 (/home/matklad/projects/stest/.cljs_node_repl/cljs/core.js:33174:9)\n    at Function.cljs.core.ex_info.cljs$core$IFn$_invoke$arity$2 (/home/matklad/projects/stest/.cljs_node_repl/cljs/core.js:33170:26)\n    at cljs$core$ex_info (/home/matklad/projects/stest/.cljs_node_repl/cljs/core.js:33156:26)\n    at stest$core_cljs$foo (/home/matklad/projects/stest/.cljs_node_repl/stest/core_cljs.js:39:25)\n    at repl:6:32\n    at repl:16:4\n    at repl:24:3\n    at repl:29:4\n    at Object.exports.runInThisContext (vm.js:74:17)"
```

Here is project.clj with all versions:

```
(defproject stest "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.7.0"]
                 [org.clojure/clojurescript "0.0-3308"]
                 [prismatic/schema "0.4.3"]]
  :profiles
  {:dev {:dependencies [[clojurescript-build "0.1.0-SNAPSHOT"]]}})
```

I'm using nodejs REPL.

**Comment by matklad** [comment]
Well, I guess it is a clojurescript bug in the end: http://dev.clojure.org/jira/browse/CLJS-985?focusedCommentId=39520#comment-39520
